language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq gdal-bin python-gdal 

install:
- pip install -r requirements.txt
- pip install nose

script: nosetests tests/ --nocapture --cover-package=utilities --with-coverage


after_success: coveralls
